/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import { useCustomizerStore } from "@/modules/Customizer/store";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";

export const Shirt = (props: any) => {
  const { nodes, materials } = useGLTF("/shirt_baked.glb");
  const { currentColor, currentDecal } = useCustomizerStore();

  const material = materials.lambert1 as THREE.MeshStandardMaterial;
  const texture = useTexture(`${currentDecal}_thumb.png`);

  useFrame((state, delta) => {
    easing.dampC(material.color, new THREE.Color(currentColor), 0.35, delta);
  });

  return (
    <mesh
      castShadow
      receiveShadow
      geometry={(nodes.T_Shirt_male as THREE.Mesh).geometry}
      material={materials.lambert1}
      rotation = {[Math.PI / 2, 0, 0]} 
      position={[0, 0, 0.30]}
      material-roughness={1}
      {...props}
      dispose={null}
    >
      <Decal
        rotation = {[Math.PI / 2, 3.1, -3.1]} 
        position={[-0.41, 0.08, -0.33]}
        scale={.14}

        map={texture}
      />
    </mesh>
  );
};

useGLTF.preload("/shirt_baked.glb");

['/react_thumb.png', '/three2_thumb.png', '/charmander_thumb.png', '/cd_thumb.png', '/orange_thumb.png'].forEach((path) => {
  useTexture.preload(path);
});
